version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2022.08
    resource_class: small
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: ls -la
      - run: bundle install
      - run: bundle exec danger --version
      - run: bundle exec danger --fail-on-errors=true
      #- run: ./gradlew androidDependencies
      #- run: ./gradlew lint test
