version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2022.08
    resource_class: small
    steps:
      - checkout
      - run: which gem
      - run: which bundle
      #- run: ./gradlew androidDependencies
      #- run: ./gradlew lint test
